### ISSUE TITLE
Missing instructions from documentation.

### ISSUE THREAD

**Issue by aesraethr** [hoover/docker-setup#69]
I followed the whole "installation" part of the documentation and it seems like the last step is missing.
Once the containers are all started, how to access the UI ? does it need an apache/nginx in front ?

I tried with an apache and ProxyPass to route traffic to the hoover-search ip, but then it prompted an error, i had to change the allowed hostnames in the settings/search.env to allow my server hostname, but then i get an infinite loading... 

What did i miss ?

**Comment by mgax** [comment]
> I followed the whole "installation" part of the documentation and it seems like the last step is missing.

It looks like the documentation for setting the http hostname is missing. Thanks for pointing this out!

**Comment by aesraethr** [comment]
do you mind giving me instructions to do so ? I will gladly update the documentation and make a pull request if you cant do it for now.

**Comment by mugurrus** [comment]
I updated the documentation on how to set up the hoover search host. If you still have issues please send me the logs for the search service.

**Comment by aesraethr** [comment]
It works, thanks, closing
