### ISSUE TITLE
Creating a collection with "_" will create issues later on while processing the files.

### ISSUE THREAD

**Issue by aesraethr** [hoover/docker-setup#73]
It should be stated in the documentation that you should name your collection with http compliant naming.
Or, every container name / hostname / url should be "url-safed" letting the user name his collections as he pleases.

`ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'snoop--luxembourg_pdf'. The domain name provided is not valid according to RFC 1034/1035.`

**Comment by mugurrus** [comment]
Resolved in this PR: https://github.com/hoover/docker-setup/pull/75
